spring.application.name=api-blank
# 1. Datos de conexión a tu base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/apiblank
spring.datasource.username=postgres
spring.datasource.password=1234

# 2. Configuración estricta de JPA (obligatorio según el profe)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false